# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python:
  - 3.6
  - 3.7
  - 3.8

# Install the pip dependencies
install:
  - pip install bcrypt requests gnupg

# Run the unit test
script:
  - python -m unittest discover
